name: test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6
      - run: make test

  lint:
    name: "tf-provider-lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bflad/tfproviderlint-github-action@master
        with:
          args: ./...

  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29

  acctest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
      - name: Bring up kafka + zk
        run: docker-compose up -d
      - name: "Run tests"
        run: |
          go install github.com/jstemmer/go-junit-report
          make testacc | go-junit-report > go-test-report.xml
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: acc-test-results.xml
          path: go-test-report.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: 'go-test-report.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
        # Use always() to always run this step to publish test results when there are test failures
        if: always()
